default:
    image: python:3.8
    before_script:
       - pip install -U pip
       - pip install poetry 
       - poetry install
stages:
    - formatting
    - test
formatting:
    script:
        - poetry run isort vibdata/ tests/
        - poetry run black --fast vibdata/ tests/
test:
    script:
        - poetry run pytest
